# Generated by Django 2.0 on 2021-11-16 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='measure_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=5)),
                ('measurement_items', models.CharField(max_length=50)),
                ('upper_limit', models.FloatField(max_length=20)),
                ('lower_limit', models.FloatField(max_length=20)),
                ('specification_center', models.FloatField(max_length=20)),
                ('measure_points', models.CharField(max_length=20)),
                ('measure_number', models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('7', '7')], max_length=5)),
                ('decimal_piaces', models.FloatField(choices=[(0.01, 0.01), (0.001, 0.001), (0.0001, 0.0001)])),
                ('image', models.ImageField(upload_to=mysite.models.path_measure_item)),
                ('image_base64_data', models.TextField(blank=True, max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='measure_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_man', models.CharField(max_length=10)),
                ('measure_number', models.CharField(max_length=200)),
                ('measure_value', models.FloatField(max_length=20)),
                ('measure_unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=5)),
                ('measure_time', models.DateTimeField()),
                ('time_now', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='measurement_work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sor_no', models.CharField(max_length=100)),
                ('number_of_parts', models.CharField(blank=True, max_length=100)),
                ('remake', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='measuring_tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=50)),
                ('tooltype', models.CharField(max_length=50)),
                ('toolprecision', models.FloatField(max_length=50)),
                ('tooltestdata', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_create_date', models.DateField(default=django.utils.timezone.now)),
                ('founder_name', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to=mysite.models.path_project)),
                ('materials', models.CharField(blank=True, max_length=100)),
                ('manufacturing_machine', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('Class', models.CharField(blank=True, max_length=100)),
                ('remake', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='work_order_measure_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=5)),
                ('measurement_items', models.CharField(max_length=50)),
                ('upper_limit', models.FloatField(max_length=20)),
                ('lower_limit', models.FloatField(max_length=20)),
                ('specification_center', models.FloatField(max_length=20)),
                ('measure_points', models.CharField(max_length=20)),
                ('measure_number', models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('7', '7')], max_length=5)),
                ('decimal_piaces', models.FloatField(choices=[(0.01, 0.01), (0.001, 0.001), (0.0001, 0.0001)])),
                ('image', models.ImageField(upload_to=mysite.models.path_work_order_measure_item)),
                ('image_base64_data', models.TextField(blank=True, max_length=100000)),
                ('measurement_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measurement_work_order')),
                ('tool_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measuring_tool')),
            ],
        ),
        migrations.AddField(
            model_name='measurement_work_order',
            name='project_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
        ),
        migrations.AddField(
            model_name='measure_values',
            name='measure_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
        ),
        migrations.AddField(
            model_name='measure_values',
            name='measure_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measuring_tool'),
        ),
        migrations.AddField(
            model_name='measure_items',
            name='tool_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measuring_tool'),
        ),
    ]
