# Generated by Django 2.0 on 2021-11-19 08:49

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to=mysite.models.path_project),
        ),
    ]
