# Generated by Django 2.0 on 2021-11-20 06:20

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20211119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default=1, upload_to=mysite.models.path_project),
            preserve_default=False,
        ),
    ]
