# Generated by Django 2.0 on 2021-11-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20211120_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_items',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.project'),
            preserve_default=False,
        ),
    ]
