# Generated by Django 2.0 on 2021-11-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_measure_items_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure_items',
            name='measure_points',
        ),
    ]
