# Generated by Django 2.0 on 2021-11-21 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_measure_items_measure_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement_work_order',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
