# Generated by Django 2.0 on 2021-11-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_measurement_work_order_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order_measure_items',
            name='measure_points',
        ),
    ]
