# Generated by Django 2.0 on 2021-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_work_order_measure_items_measure_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_measure_items',
            name='image_base64_data',
            field=models.TextField(blank=True),
        ),
    ]
