# Generated by Django 2.0 on 2021-11-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20211123_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order_measure_items',
            name='decimal_piaces',
        ),
    ]
