# Generated by Django 2.0 on 2021-11-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_remove_work_order_measure_items_decimal_piaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='measure_work_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.measurement_work_order'),
            preserve_default=False,
        ),
    ]
