# Generated by Django 2.0 on 2021-11-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_measure_values_measure_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='measure_work_order_measure_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.work_order_measure_items'),
            preserve_default=False,
        ),
    ]
