# Generated by Django 2.0 on 2021-11-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_measure_values_measure_work_order_measure_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure_values',
            name='measure_number',
        ),
    ]
