# Generated by Django 2.0 on 2021-12-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_measurement_work_order_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='measure_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
