# Generated by Django 2.0 on 2021-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_measure_values_measure_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure_values',
            name='remake',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
