# Generated by Django 2.0 on 2021-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_measure_values_remake'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement_work_order',
            name='measure_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
