# Generated by Django 2.0 on 2021-12-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_measurement_work_order_measure_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_order_appearance_defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64_image', models.CharField(max_length=10000)),
                ('part_number', models.CharField(max_length=10)),
                ('remake', models.CharField(max_length=200)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measurement_work_order')),
            ],
        ),
    ]
