# Generated by Django 2.0 on 2021-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20211206_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_appearance_defect',
            name='part_number',
            field=models.TextField(max_length=10),
        ),
    ]
