# Generated by Django 2.0 on 2021-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20211208_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order_appearance_defect',
            name='manufacturing_order',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
