# Generated by Django 2.0 on 2021-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20211208_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order_measure_items',
            name='manufacturing_order',
        ),
        migrations.AddField(
            model_name='measurement_work_order',
            name='manufacturing_order',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
