# Generated by Django 2.0 on 2021-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20211208_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement_work_order',
            name='manufacturing_order',
            field=models.CharField(max_length=100),
        ),
    ]
