# Generated by Django 2.0 on 2021-12-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20211208_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure_items',
            name='decimal_piaces',
        ),
    ]
