# Generated by Django 2.0 on 2021-12-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_remove_measure_items_decimal_piaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_order_parts_reamke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('remake', models.TextField(blank=True, max_length=500)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.measurement_work_order')),
            ],
        ),
    ]
