# Generated by Django 3.2.12 on 2022-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_remove_project_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order_parts_reamke',
            name='part_type',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
