# Generated by Django 3.2.12 on 2022-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_work_order_parts_reamke_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_parts_reamke',
            name='part_type',
            field=models.CharField(choices=[('type_1', 'type_1'), ('type_2', 'type_2'), ('type_3', 'type_3')], max_length=10),
        ),
    ]
