# Generated by Django 3.2.12 on 2022-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_alter_work_order_parts_reamke_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure_values',
            name='measure_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='work_order_parts_reamke',
            name='part_type',
            field=models.CharField(choices=[('特採', '特採'), ('報廢', '報廢'), ('良品', '良品')], max_length=10),
        ),
    ]
